
#全局配置文件
server:
  port: 8080

spring:
  datasource:
    username: root
    password: smart
    url: jdbc:mysql://192.168.2.106:3306/springseed?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    async:
      request-timeout: 30000

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.aweikn.springseed.entity






#showSql
logging:
  level:
    com:
      example:
        mapper : debug




